version: '3'
services:
  app:
    build: .
    container_name: pokemon_battle_app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - POKEAPI_BASE_URL=${POKEAPI_BASE_URL}
    ports:
      - "5001:5001"
    volumes:
      - .:/app
