version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql://user:password@db/pokemon_db
      - CACHE_URL=redis://cache
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pokemon_db
  cache:
    image: redis